name: Nintendo Wii U

on: [push, pull_request]

jobs:
  WiiU-Release:
    runs-on: ubuntu-latest

    container:
      image: docker://devkitpro/devkitppc
      options: --cpus 2

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure
        run: /opt/devkitpro/portlibs/wiiu/bin/powerpc-eabi-cmake -S . -B build

      - name: Build
        run: make -C build

      - id: commit
        uses: pr-mpt/actions-commit-hash@v1

      - uses: actions/upload-artifact@v4
        with:
          name: Nintendo Wii U-${{ steps.commit.outputs.short }}
          path: |
            build/*.elf
            build/*.wuhb

  WiiU-Debug:
    runs-on: ubuntu-latest

    container:
      image: docker://devkitpro/devkitppc
      options: --cpus 2

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure
        run: /opt/devkitpro/portlibs/wiiu/bin/powerpc-eabi-cmake -DCMAKE_BUILD_TYPE=Debug -S . -B build

      - name: Build
        run: make -C build

      - id: commit
        uses: pr-mpt/actions-commit-hash@v1

      - uses: actions/upload-artifact@v4
        with:
          name: Nintendo Wii U (Debug)-${{ steps.commit.outputs.short }}
          path: |
            build/*.elf
            build/*.wuhb
