name: Nintendo 3DS

on: [push, pull_request]

jobs:
  N3DS-Release:
    runs-on: ubuntu-latest

    container:
      image: docker://devkitpro/devkitarm
      options: --cpus 2

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure
        run: /opt/devkitpro/portlibs/3ds/bin/arm-none-eabi-cmake -S . -B build

      - name: Build
        run: make -C build

      - id: commit
        uses: pr-mpt/actions-commit-hash@v1

      - uses: actions/upload-artifact@v4
        with:
          name: Nintendo 3DS-${{ steps.commit.outputs.short }}
          path: |
            build/*.elf
            build/*.3dsx

  N3DS-Debug:
    runs-on: ubuntu-latest

    container:
      image: docker://devkitpro/devkitarm
      options: --cpus 2

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure
        run: /opt/devkitpro/portlibs/3ds/bin/arm-none-eabi-cmake -DCMAKE_BUILD_TYPE=Debug -S . -B build

      - name: Build
        run: make -C build

      - id: commit
        uses: pr-mpt/actions-commit-hash@v1

      - uses: actions/upload-artifact@v2
        with:
          name: Nintendo 3DS (Debug)-${{ steps.commit.outputs.short }}
          path: |
            build/*.elf
            build/*.3dsx
